export const CA = 'COMING';
export const TELEGRAM = 'https://t.me/alonthealien'
export const TWITTER = 'https://twitter.com/ALONTHEALIEN'
export const TELEGRAM_DEV = 'https://t.me/lettodev'
export const BUY_LING = 'Coming Soon'
export const DEXSCREENER = 'Coming Soon'
export const RAYDIUM = 'Coming Soon'
export const JUPITER = 'Coming Soon'
export const DEXTOOLS = 'Coming Soon'
