export const CA = 'CKvHs1gAdyJUw3GoWQmmQ3fRVWxMqiKv841L7hmfFHyy';
export const TELEGRAM = 'https://twitter.com/ALONDEALIEN'
export const TWITTER = 'https://twitter.com/ALONTHEALIEN'
export const TELEGRAM_DEV = 'https://t.me/lettodev'
export const BUY_LING = 'Coming Soon'
export const DEXSCREENER = 'Coming Soon'
export const RAYDIUM = 'Coming Soon'
export const JUPITER = 'Coming Soon'
export const DEXTOOLS = 'Coming Soon'
