import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <head>
        <script
          type="module"
          src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js"
        ></script>
      </head>
      <body>
        {" "}
        <>
          {/* @ts-ignore */}
          <model-viewer
            class={"w-full min-h-screen"}
            src="alpha-blend-litmus.glb"
            ar
            ar-modes="webxr scene-viewer quick-look"
            camera-controls
            tone-mapping="neutral"
            poster="poster.webp"
            shadow-intensity="1"
          >
            {/* @ts-ignore */}
          </model-viewer>
        </>
      </body>
    </html>
  );
}
